In [2]:
import requests
from bs4 import BeautifulSoup as bs
import mysql.connector
import time

def hackerrank(link):
    link = link.strip()
    r = requests.get(link,headers={"User-Agent":"Mozilla/5.0"})
    soup = bs(r.content,"html.parser")
    badges = soup.find_all("div",attrs={"class":"hacker-badge"})
    badge_count = len(badges)
    
    python,c,cpp,java,mysql,ps = 0,0,0,0,0,0

    print("Total Badges earned: "+str(badge_count))
    for tag in badges:       
        stars = tag.find_all("svg",attrs={"class":"badge-star"})
        name = str(tag.get_text())
        count = str(len(stars))
        if ("Python" in name): python = count
        elif ("CPP" in name): cpp = count
        elif ("C" in name): c = count
        elif ("Java" in name): java = count
        elif ("Sql" in name): mysql = count
        elif ("Problem" in name): ps = count
    
    return badge_count,python,c,cpp,java,mysql,ps

conn = mysql.connector.connect(host="localhost",user="root",passwd="562004",database="codingdashboard")
cursor = conn.cursor()
cursor.execute("SELECT REGISTERNUMBER,PROFILELINK FROM CSE_GENERAL_HR;")
results = cursor.fetchall()

for row in results:
    regno = row[0]
    link = row[1]

    print("RegNo: ",regno)
    if (len(link) == 0):
        L = ['0','0','0','0','0','0','0']
    else:
        link = link.strip()
        L = hackerrank(link)
    L = list(L)
    L.append(regno)

    query = "UPDATE CSE_GENERAL_HR SET BADGES_COUNT={0}, PYTHON={1}, C={2}, CPP={3}, JAVA={4}, MYSQL={5}, PROBLEMSOLVING={6} WHERE REGISTERNUMBER={7};".format(L[0],L[1],L[2],L[3],L[4],L[5],L[6],L[7])
    print(query)
    cursor.execute(query)
    cursor.execute("COMMIT;")
    conn.commit()

conn.commit()
conn.close()

RegNo:  210421104001
Total Badges earned: 1
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=1, PYTHON=3, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104001;
RegNo:  210421104002
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104002;
RegNo:  210421104003
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104003;
RegNo:  210421104004
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104004;
RegNo:  210421104005
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104005;
RegNo:  210421104006
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104006;
RegNo:  210421104009
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104009;
RegNo:  210421104010
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104010;
RegNo:  210421104011
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104011;
RegNo:  210421104012
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104012;
RegNo:  210421104013
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104013;
RegNo:  210421104014
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104014;
RegNo:  210421104015
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104015;
RegNo:  210421104017
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104017;
RegNo:  210421104018
Total Badges earned: 3
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=3, PYTHON=2, C=4, CPP=1, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104018;
RegNo:  210421104019
Total Badges earned: 1
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=1, PYTHON=3, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104019;
RegNo:  210421104020
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104020;
RegNo:  210421104021
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104021;
RegNo:  210421104022
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104022;
RegNo:  210421104023
Total Badges earned: 2
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=2, PYTHON=2, C=0, CPP=0, JAVA=0, MYSQL=1, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104023;
RegNo:  210421104024
Total Badges earned: 2
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=2, PYTHON=0, C=0, CPP=2, JAVA=4, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104024;
RegNo:  210421104025
Total Badges earned: 1
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=1, PYTHON=0, C=1, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104025;
RegNo:  210421104026
Total Badges earned: 2
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=2, PYTHON=0, C=3, CPP=5, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104026;
RegNo:  210421104027
Total Badges earned: 1
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=1, PYTHON=0, C=1, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104027;
RegNo:  210421104028
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104028;
RegNo:  210421104030
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104030;
RegNo:  210421104032
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104032;
RegNo:  210421104033
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104033;
RegNo:  210421104034
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104034;
RegNo:  210421104035
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104035;
RegNo:  210421104036
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104036;
RegNo:  210421104041
Total Badges earned: 2
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=2, PYTHON=4, C=0, CPP=0, JAVA=0, MYSQL=2, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104041;
RegNo:  210421104042
Total Badges earned: 1
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=1, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104042;
RegNo:  210421104044
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104044;
RegNo:  210421104047
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104047;
RegNo:  210421104048
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104048;
RegNo:  210421104049
Total Badges earned: 2
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=2, PYTHON=1, C=1, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104049;
RegNo:  210421104050
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104050;
RegNo:  210421104051
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104051;
RegNo:  210421104052
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104052;
RegNo:  210421104053
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104053;
RegNo:  210421104054
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104054;
RegNo:  210421104055
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104055;
RegNo:  210421104056
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104056;
RegNo:  210421104057
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104057;
RegNo:  210421104058
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104058;
RegNo:  210421104059
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104059;
RegNo:  210421104060
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104060;
RegNo:  210421104061
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104061;
RegNo:  210421104304
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104304;
RegNo:  210421104306
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104306;
RegNo:  210421104431
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104431;
RegNo:  210421104062
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104062;
RegNo:  210421104063
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104063;
RegNo:  210421104064
Total Badges earned: 4
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=4, PYTHON=3, C=1, CPP=0, JAVA=1, MYSQL=0, PROBLEMSOLVING=2 WHERE REGISTERNUMBER=210421104064;
RegNo:  210421104065
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104065;
RegNo:  210421104066
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104066;
RegNo:  210421104068
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104068;
RegNo:  210421104069
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104069;
RegNo:  210421104070
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104070;
RegNo:  210421104071
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104071;
RegNo:  210421104072
Total Badges earned: 1
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=1, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=1, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104072;
RegNo:  210421104073
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104073;
RegNo:  210421104074
Total Badges earned: 2
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=2, PYTHON=3, C=4, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104074;
RegNo:  210421104075
Total Badges earned: 4
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=4, PYTHON=2, C=1, CPP=0, JAVA=2, MYSQL=0, PROBLEMSOLVING=1 WHERE REGISTERNUMBER=210421104075;
RegNo:  210421104076
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104076;
RegNo:  210421104077
Total Badges earned: 2
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=2, PYTHON=1, C=2, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104077;
RegNo:  210421104078
Total Badges earned: 1
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=1, PYTHON=1, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104078;
RegNo:  210421104079
Total Badges earned: 3
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=3, PYTHON=4, C=3, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=3 WHERE REGISTERNUMBER=210421104079;
RegNo:  210421104080
Total Badges earned: 1
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=1, PYTHON=4, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104080;
RegNo:  210421104081
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104081;
RegNo:  210421104082
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104082;
RegNo:  210421104083
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104083;
RegNo:  210421104084
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104084;
RegNo:  210421104085
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104085;
RegNo:  210421104086
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104086;
RegNo:  210421104087
Total Badges earned: 1
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=1, PYTHON=4, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104087;
RegNo:  210421104088
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104088;
RegNo:  210421104089
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104089;
RegNo:  210421104090
Total Badges earned: 3
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=3, PYTHON=2, C=0, CPP=3, JAVA=0, MYSQL=0, PROBLEMSOLVING=2 WHERE REGISTERNUMBER=210421104090;
RegNo:  210421104091
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104091;
RegNo:  210421104092
Total Badges earned: 3
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=3, PYTHON=1, C=1, CPP=0, JAVA=1, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104092;
RegNo:  210421104093
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104093;
RegNo:  210421104094
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104094;
RegNo:  210421104095
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104095;
RegNo:  210421104096
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104096;
RegNo:  210421104097
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104097;
RegNo:  210421104098
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104098;
RegNo:  210421104099
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104099;
RegNo:  210421104100
Total Badges earned: 3
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=3, PYTHON=5, C=4, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=1 WHERE REGISTERNUMBER=210421104100;
RegNo:  210421104101
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104101;
RegNo:  210421104102
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104102;
RegNo:  210421104103
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104103;
RegNo:  210421104105
Total Badges earned: 2
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=2, PYTHON=5, C=5, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104105;
RegNo:  210421104106
Total Badges earned: 1
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=1, PYTHON=5, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104106;
RegNo:  210421104107
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104107;
RegNo:  210421104108
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104108;
RegNo:  210421104109
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104109;
RegNo:  210421104110
Total Badges earned: 5
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=5, PYTHON=5, C=5, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=3 WHERE REGISTERNUMBER=210421104110;
RegNo:  210421104111
Total Badges earned: 2
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=2, PYTHON=2, C=4, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104111;
RegNo:  210421104112
Total Badges earned: 2
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=2, PYTHON=5, C=5, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104112;
RegNo:  210421104113
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104113;
RegNo:  210421104114
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104114;
RegNo:  210421104115
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104115;
RegNo:  210421104116
Total Badges earned: 2
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=2, PYTHON=2, C=1, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104116;
RegNo:  210421104117
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104117;
RegNo:  210421104118
Total Badges earned: 1
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=1, PYTHON=0, C=0, CPP=0, JAVA=1, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104118;
RegNo:  210421104119
Total Badges earned: 1
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=1, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=1 WHERE REGISTERNUMBER=210421104119;
RegNo:  210421104120
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104120;
RegNo:  210421104121
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104121;
RegNo:  210421104122
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104122;
RegNo:  210421104123
Total Badges earned: 0
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=0, PYTHON=0, C=0, CPP=0, JAVA=0, MYSQL=0, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104123;
RegNo:  210421104152
Total Badges earned: 3
UPDATE CSE_GENERAL_HR SET BADGES_COUNT=3, PYTHON=0, C=1, CPP=2, JAVA=0, MYSQL=2, PROBLEMSOLVING=0 WHERE REGISTERNUMBER=210421104152;
RegNo:  210421104155
Total Badges earned: 1